name: Theme Tests - master

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run theme tests
        uses: GreenMeteor/actions/.github/workflows/theme-tests-master.yml@main
        with:
          theme-name: Material
