name: Theme Tests - master

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    uses: GreenMeteor/actions/.github/workflows/theme-tests-master.yml@main
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php: ['7.4', '8.0', '8.1']
        mysql: ['5.7']
    with:
      theme-name: Material
